# Generated by Django 2.2.5 on 2020-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
