# Generated by Django 2.2.5 on 2020-01-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='primaryCategory',
        ),
    ]
